import {config as buildConfig} from './wdio.conf';

// The comparison feature files are generated by the comparison tests generator.feature based on the IDs it finds in the databases, so run that first using the following command:
// npx wdio run wdio.comparisons.conf.ts dbserver:<dbserver> dbserver2:<dbserver2> days:<days> --suite generate

// Then run the tests themselves with the following command
// npx wdio run wdio.comparisons.conf.ts server:<dbserver> server2:<dbserver2> user:<user> password:<password>
buildConfig.specs = [
    './src/features/comparisons/comparisonFeatureFileGenerator.feature',
    './src/features/comparisons/reportsComparison.feature',
    './src/features/comparisons/queriesComparison.feature',
    './src/features/comparisons/dashboardsComparison.feature'
];

buildConfig.suites = {
	generate: [
		'./src/features/comparisons/comparisonFeatureFileGenerator.feature'
	],
    reportsComparison: [
        './src/features/comparisons/reportsComparison.feature',
    ],
    queriesComparison: [
        './src/features/comparisons/queriesComparison.feature',
    ],
    dashboardsComparison: [
        './src/features/comparisons/dashboardsComparison.feature',
    ]
};

export const config = buildConfig;